# 应用服务 WEB 访问端口
server:
  port: 8095
spring:
  redis:
    database: 1
    host: www.digital-nursing.com
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 2000
    lettuce:
      pool:
        enabled: true
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 2000
    connect-timeout: 30000ms


